### ISSUE TITLE
panic: unable to retrieve the complete list of server APIs

### ISSUE THREAD

**Issue by guettli** [guettli/check-conditions#1]
```
❯ go run github.com/guettli/check-conditions@latest all
panic: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: stale GroupVersion discovery: metrics.k8s.io/v1beta1

goroutine 1 [running]:
github.com/guettli/check-conditions/cmd.runAll({0x0?})
        /home/guettli/go/pkg/mod/github.com/guettli/check-conditions@v0.0.0-20230918080552-3b935fcc2a3d/cmd/all.go:90 +0x465
github.com/guettli/check-conditions/cmd.glob..func1(0xc000221c00?, {0x15fa007?, 0x4?, 0x15fa00b?})
        /home/guettli/go/pkg/mod/github.com/guettli/check-conditions@v0.0.0-20230918080552-3b935fcc2a3d/cmd/all.go:27 +0x1a
github.com/spf13/cobra.(*Command).execute(0x22d7d80, {0x231ad60, 0x0, 0x0})
        /home/guettli/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x22d7aa0)
        /home/guettli/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /home/guettli/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/guettli/check-conditions/cmd.Execute()
        /home/guettli/go/pkg/mod/github.com/guettli/check-conditions@v0.0.0-20230918080552-3b935fcc2a3d/cmd/root.go:18 +0x1a
main.main()
        /home/guettli/go/pkg/mod/github.com/guettli/check-conditions@v0.0.0-20230918080552-3b935fcc2a3d/main.go:10 +0xf
exit status 2
```

**Comment by guettli** [comment]
fixed.
